// <auto-generated />
using System;
using PainelComercial.Api.Estoque;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PainelComercial.Api.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    [Migration("20261007022931_ChaveIdempotencia")]
    partial class ChaveIdempotencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PainelComercial.Api.Estoque.Movimentacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaveIdempotencia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstoqueAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstoqueFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("CodigoProduto");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("PainelComercial.Api.Estoque.Produto", b =>
                {
                    b.Property<int>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("CodigoProduto");

                    b.ToTable("Produtos", t =>
                        {
                            t.HasCheckConstraint("CK_Produtos_EstoqueNaoNegativo", "\"Estoque\" >= 0");
                        });
                });

            modelBuilder.Entity("PainelComercial.Api.Estoque.Movimentacao", b =>
                {
                    b.HasOne("PainelComercial.Api.Estoque.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
